version: '3.7'
networks:
  privnet:


services:
  backend:
    container_name: backend
    restart: always
    build: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: testing
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - privnet

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - privnet

volumes:
  postgres_data:
